In [1]:
import numpy as np
array = np.array([
    [1,3,5],
    [4,6,9]
])
print(array)

[[1 3 5]
 [4 6 9]]


In [3]:
print("array矩阵的维度是%d"%array.ndim)

array矩阵的维度是2


In [7]:
print("行数和列数",array.shape)

行数和列数 (2, 3)


In [8]:
print("元素个数：",array.size)

元素个数： 6


In [12]:
import numpy as np
# 一维array
a=np.array([2,3,4],dtype=np.int64)
print(a)
print(a.dtype)

[2 3 4]
int64


In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
a = np.ones((3,4),dtype=np.int64)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
a=np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
a = np.arange(0,12,2)
print(a)

[ 0  2  4  6  8 10]


In [29]:
b = a.reshape((2,3))
print(b)

[[ 0  2  4]
 [ 6  8 10]]


In [31]:
l = np.linspace(1,10,20)
print(l)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [32]:
l1= l.reshape((5,4))
print(l1)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [33]:
import numpy as np
# 一维矩阵运算
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

[10 20 30 40] [0 1 2 3]


In [34]:
c = a - b
print(c)

[10 19 28 37]


In [35]:
print(a*b) # 若用a.dot(b),则为各维之和

[  0  20  60 120]


In [36]:
# 在Numpy中，想要求出矩阵中各个元素的乘方需要依赖双星符号 **，以二次方举例，即：
c = b**2
print(c)

[0 1 4 9]


In [37]:
# Numpy中具有很多的数学函数工具
c = np.sin(a)
print(c)

[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [38]:
print(b<2)

[ True  True False False]


In [39]:
a = np.array([1,1,4,3])
b = np.arange(4)
print(a==b)

[False  True False  True]


In [41]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [42]:
c = a.dot(b)
print(c)

[[2 4]
 [2 3]]


In [43]:
c = np.dot(a,b)
print(c)

[[2 4]
 [2 3]]


In [44]:
a = np.random.random((2,4))
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print("sum=",np.sum(a,axis=1))
print("min=",np.min(a,axis=0))
print("max=",np.max(a,axis=1))

4.413713672983667
0.005365421446028584
0.9634453061836982
sum= [1.53009297 2.8836207 ]
min= [0.07609669 0.86806833 0.00536542 0.44645214]
max= [0.86806833 0.96344531]


In [45]:
import numpy as np
A = np.arange(2,14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [46]:
# 最小元素索引
print(np.argmin(A)) # 0

0


In [47]:
print(np.argmax(A))

11


In [49]:
print(np.mean(A))
print(np.average(A))
print(A.mean())

7.5
7.5
7.5


In [51]:
print(np.median(A))

7.5


In [52]:
print(np.cumsum(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [55]:
# 累差运算
B = np.array([[3,5,9],
              [4,8,10]])
print(np.diff(B))

[[2 4]
 [4 2]]


In [56]:
C = np.array([[0,5,9],
              [4,0,10]])
print(np.nonzero(B))
print(np.nonzero(C))

(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 1, 2, 0, 1, 2], dtype=int64))
(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))


In [57]:
# 仿照列表排序
A = np.arange(14,2,-1).reshape((3,4)) # -1表示反向递减一个步长
print(A)

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]


In [58]:
print(np.sort(A))

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [59]:
print(np.transpose(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [60]:
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [61]:
print(np.clip(A,5,9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [62]:
import numpy as np
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
B = A.reshape(3,4)
print(B)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [67]:
print(B[2])

[11 12 13 14]


In [68]:
print(B[0][2])

5


In [69]:
print(B[0,2])

5


In [70]:
print(B[1,1:3])

[8 9]


In [71]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [72]:
for column in B.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [75]:
A= np.arange(3,15).reshape((3,4))
print(A)
print(A.flatten())

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [77]:
for item in A.flatten():
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [78]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))

[[1 1 1]
 [2 2 2]]


In [79]:
C = np.vstack((A,B))
print(C)

[[1 1 1]
 [2 2 2]]


In [80]:
print(A.shape,B.shape,C.shape)

(3,) (3,) (2, 3)


In [81]:
D = np.hstack((A,B))
print(D)

[1 1 1 2 2 2]


In [82]:
print(A.shape,B.shape,C.shape,D.shape)

(3,) (3,) (2, 3) (6,)


In [83]:
print(A[np.newaxis,:])

[[1 1 1]]


In [84]:
print(A[np.newaxis,:].shape)

(1, 3)


In [85]:
print(A[:,np.newaxis])

[[1]
 [1]
 [1]]


In [96]:
print("-------------")
A = np.array([1,1,1])
B = np.array([2,2,2])
print(A[:,np.newaxis].shape)

-------------
(3, 1)


In [97]:
A = A[:,np.newaxis]
B = B[:,np.newaxis]
print(A)

[[1]
 [1]
 [1]]


In [98]:
print(B)

[[2]
 [2]
 [2]]


In [99]:
C = np.concatenate((A,B,B,A),axis=0)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [102]:
C = np.concatenate((A,B),axis=1)
print(C)

[[1 2]
 [1 2]
 [1 2]]


In [104]:
print("-----------------")
A = np.arange(8).reshape(2,4)
B = np.arange(8).reshape(2,4)
print(A)
print(B)
print("-----------------")

-----------------
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
-----------------


In [105]:
C = np.concatenate((A,B),axis=0)
print(C)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]


In [106]:
C = np.concatenate((A,B),axis=1)
print(C)

[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


In [107]:
import numpy as np
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [108]:
print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [110]:
print(np.split(A,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [111]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [112]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [113]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
